project:
  type: website
  output-dir: docs

website:
  title: "Основы пространственного анализа"
  page-footer: |
        © 2026, Татьяна Балтыжакова, Институт дизайна и урбанистики, Университет ИТМО
  navbar:
    left:
      - href: index.qmd
        text: О курсе
      - href: lectures.qmd
        text: Лекции
      - sidebar:practice
      - href: exam.qmd
        text: Зачет
      

    right: 
      - href: https://t.me/geomess
        icon: telegram
      - icon: github
        href: https://github.com/baltti/bachelor-spatial-analysis   

  sidebar:
    - id: practice
      logo: "images/logo.png"
      pinned: true
      align: center
      title: "Практикум"
      style: "docked"
      collapse-level: 1
      contents:
         - section: Работа с данными дистанционного зондирования
           contents:
            - 01-remote-sensing-data.qmd
            - 02-remote-sensing-basics.qmd
            - 03-vegetation-indices.qmd
            - 04-surface-temperature.qmd
            - 05-image-classification.qmd
         - 06-location-allocation.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    
lang: ru-RU    
language: custom.yml

editor: visual

