---
title: "Зачет"
date: last-modified
date-format: "D MMMM YYYY"
---

# Система оценивания

✅ меньше 60 баллов - "неудовлетворительно", FX

✅ от 60 до 67 баллов включительно - "удовлетворительно", E

✅ более 67 и до 74 баллов включительно - "удовлетворительно", D

✅ более 74 и до 83 баллов включительно - "хорошо", С

✅ более 83 и до 90 баллов включительно - "хорошо", В

✅ более 90 и до 103 баллов включительно - "отлично", А

# Получение дифференциального зачета

Оценка за зачет складывается из двух составляющих:

| № | Составляющая зачета | Максимальное количество баллов |
|----|----|----|
| 1 | Практическая работа "**Анализ территории"** | 60 баллов |
| 2 | Устный зачет | 40 баллов |

::: callout-important
Если вы сдали практическую работу на максимальный балл - 60, то вы можете получить "удовлетворительно" автоматически.

Если вы рассчитываете на более высокую оценку, то необходимо будет сдать экзамен.
:::

# Примерный перечень вопросов

## Анализ данных дистанционного зондирования

1.  Что такое дистанционное зондирование?

2.  Как можно классифицировать спутниковые снимки?

3.  Что такое пространственное/спектральное разрешение?

4.  На чем основан принцип расчета спектральных индексов?

5.  Как из снимков для отдельных каналов может быть составлен цветной снимок?

6.  Какие существуют спектральные индексы?

7.  Для чего составляются композиты в искусственных цветах?

## Анализ доступности и обеспеченности

1.  Что такое доступность объекта?

2.  Что такое обеспеченность сервисом?

3.  Как может быть рассчитана доступность?

4.  Как рассчитывается обеспеченность?

5.  Что такое анализ размещения-распределения?

6.  Приведите пример применения анализа размещения-распределения для решения городских задач.

## Гравитационные модели

1.  Первый закон географии.
2.  Что такое затухание расстояния?
3.  Что такое сжатие пространства и времени?
4.  Что является общим принципом гравитационных моделей?
5.  Гравитационная модель Хаффа.
6.  Какие есть гравитационные модели?
7.  Как применяются гравитационные модели?
8.  От чего зависит вероятность использования сервиса в гравитационной модели Хаффа?
9.  Как на вероятность использования сервиса влияет расстояние/площадь сервиса?

## Анализ точечных паттернов и кластеризация

1.  Что такое точечный паттерн?
2.  Какие виды точечных паттернов есть?
3.  Основные виды пространственных эффектов точечного процесса.
4.  Основные подходы к анализу точечных паттернов.
5.  В чем разница между глобальной и локальной плотностью?
6.  Анализ точечных паттернов на основе плотности.
7.  Анализ точечных паттернов на основе расстояния между наблюдениями.
8.  Ядерная оценка плотности.
9.  Анализ ближайших соседей.
10. Что такое кластеризация?
11. Методы кластеризации.
