---
title: "Основы пространственного анализа"
date: last-modified
date-format: "D MMMM YYYY"
number-sections: false
author:
  - affiliation: Институт дизайна и урбанистики, Университет ИТМО 
    name: Балтыжакова Татьяна
---

## О чем курс?

Курс является продолжением курса дисциплины прошлого семестра "[Геоинформационные системы](https://baltti.github.io/bachelor-gis-course/)".

В этом курсе мы попробуем понять, как именно можно анализировать городскую среду и рассчитывать некоторые важные показатели.

Как и в прошлом семестре мы продолжим преимущественно работать в программе QGIS.

::: callout-note
Если у вас осталась установка программы с прошлого семестра, то обновлять ее не нужно. Вы можете пользоваться той версией, что у вас установлена.
:::

# Примерный перечень тем курса

1.  Использование материалов дистанционного зондирования Земли для анализа городской среды

2.  Анализ доступности и обеспеченности объектами инфраструктуры

3.  Интерполяция данных

4.  Растровый оверлей

5.  Автоматизация и построение геомоделей
